### ISSUE TITLE
请问如何搭建环境与运行测试？

### ISSUE THREAD

**Issue by nobodxbodon** [jack9603301/nginx-enhance-module#1]
希望工具链支持中文命名。

**Comment by jack9603301** [comment]
这个项目其实是一个集成模块的项目，编译方式和nginx官方的一致，但我尚未测试过和tengine的模块兼容性

此项目提供了一种方式，可以将类似tengine的一些模块和http3包含进一个项目，并在同一个项目中提供了常用的模块，用户可以根据需要使用特定的插件模块

这个项目也许还不是特别完善，欢迎贡献

**此项目是一种探索，其中包括了http3的支持模块**

这是一个简单的实例

```
git clone https://github.com/jack9603301/nginx-enhance-module --recurse-submodules
./download_dependency.py
cd nginx 
./configure .... --add-module=../modules/.....
```

**Comment by nobodxbodon** [comment]
运行`./download_dependency.py`时中途报错：
```
I: Module ngx_http_auth_request_module performs cloning /Users/xuanwu/git/nginx-enhance-module/tmp/modules/ngx_http_auth_request_module
Cloning into '/Users/xuanwu/git/nginx-enhance-module/tmp/modules/ngx_http_auth_request_module'...
fatal: unable to access 'http://mdounin.ru/hg/ngx_http_auth_request_module/': The requested URL returned error: 400
E: Module ngx_http_auth_request_module Execution command error, termination
```

**Comment by jack9603301** [comment]
https://github.com/jack9603301/nginx-enhance-module/blob/main/modules.yaml

**Comment by jack9603301** [comment]
在这个文件找到ngx_http_auth_request_module模块，把配置删掉

**Comment by jack9603301** [comment]
这个链接可能要翻墙，我的正常

**Comment by nobodxbodon** [comment]
现在美国西岸，应该不是翻墙的问题。nginx 构建和测试的方法可否分享链接？

**Comment by nobodxbodon** [comment]
依赖模块仍然没下完，期间不断有重试。如果这是对 nginx 的补丁，不如我直接对 nginx 源码的一小部分做中文化？

**Comment by jack9603301** [comment]
http://nginx.org/en/docs/configure.html
这是源码编译
应该是因为国内的原因 其实 这个项目是一些补丁和模块，欢迎增加辅助性脚本和改进

你可以编写补丁文件，对源码进行中文化，并放入patch，但是我劝你谨慎进行，因为这不符合国际规范，顶多对国内部分人有用

**Comment by nobodxbodon** [comment]
本演示仅为验证标识符翻译的技术可行性。无意对项目主库提交任何中文化相关 pr。
请你选择熟悉的项目只为在中文化时可以选取你最了解的部分，以方便合作进行。

**Comment by jack9603301** [comment]
你可以对py脚本进行中文化尝试

**Comment by jack9603301** [comment]
可别告诉我只是提示中文了

**Comment by nobodxbodon** [comment]
是指 https://github.com/jack9603301/nginx-enhance-module/blob/main/download_dependency.py 吗？

**Comment by jack9603301** [comment]
对，同时也欢迎你为其增加胶合辅助脚本，方便为用户定制化集成

**Comment by jack9603301** [comment]
这个代码库主要是一种尝试，将一些好的模块通过这个库提供一个方便的途径集成到nginx

**Comment by jack9603301** [comment]
所以我将nginx作为submodule链接到上游

**Comment by nobodxbodon** [comment]
请阅 [标识符中文化演示 ](https://github.com/nobodxbodon/nginx-enhance-module/commit/875d9abf12a0f5118dff32a40ec790e4fd022878)。

个人对 nginx 不熟，有机会再深入研究。

**Comment by jack9603301** [comment]
好吧，只是替换的话确实，但是总觉得怪怪的。大多数专业开发的不会这样写，你这种写法可能适合那些随便写几个脚本的外行。

代码少还好，多的话，到时候，很不习惯的，而且难以维护

只能说我们走的不是一条路

虽说如此，如果你愿意，欢迎你为其添加胶合辅助脚本

另外，服务器通常不会安装中文支持，在这些系统上，你的脚本就是乱码

**Comment by nobodxbodon** [comment]
既然演示完成，还是回 gitee 继续吧。
